### ISSUE TITLE
Comments -->

### ISSUE THREAD

**Issue by F1LT3R** [isRuslan/vim-es6#12]
It seems comments are not being aded to the HI Comment group?

Example:

``` javascript
// Single Line Slashed Comment
--> Single Line Arrow Comment
```

I would think these should both be the same color using your plugin?

Nice work BTW! Thanks for the effort. ES6 is definitely a nicer experience with your plugin enabled.

**Comment by isRuslan** [comment]
Hi @F1LT3R, thanks for a feedback! And I'm a little bit confusing, is `--> Single Line Arrow Comment` a valid javascript comment?

**Comment by F1LT3R** [comment]
> is `--> Single Line Arrow Comment` a valid javascript comment?

Apparently it is.

Allegedly available since forever: https://hacks.mozilla.org/2015/06/es6-in-depth-arrow-functions/
And recently ratified: https://tc39.github.io/ecma262/#prod-annexB-SingleLineHTMLOpenComment

## Example

Create **`test.js`** like so:

```
--> A comment
console.log(1+2);
```

Run with node:

``` shell
node test.js
# outputs "3"
```

No errors.

**Comment by isRuslan** [comment]
Oh, you mean HTML-like pair comment `<!-- -->`, following your link in specification (annex B): https://tc39.github.io/ecma262/#sec-additional-ecmascript-features-for-web-browsers

> This annex describes various legacy features and other characteristics of web browser based ECMAScript implementations. All of the language features and behaviours specified in this annex have one or more undesirable characteristics and in the absence of legacy usage would be removed from this specification. However, the usage of these features by large numbers of existing web pages means that web browsers must continue to support them. The specifications in this annex define the requirements for interoperable implementations of these legacy features.

This is just exist because old browsers still support this. I think this type of comments belongs to HTML files and should not be used in javascript.

**Comment by F1LT3R** [comment]
Makes sense.

On Mon, Sep 12, 2016 at 12:45 PM, Ruslan Ismagilov <notifications@github.com
