### ISSUE TITLE
Template strings

### ISSUE THREAD

**Issue by rreusser** [isRuslan/vim-es6#2]
Would be great if it supported [template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings)! I have work to do so can't investigate this at the moment, but since it's nearly identical to ruby string interpolation, this may be a good starting point:

https://github.com/vim/vim/blob/db9bc0b7931d252cf578c1cd298ac905b904ebe7/runtime/syntax/ruby.vim#L43

**Comment by isRuslan** [comment]
Thanks for suggestion, I'll check that.

**Comment by isRuslan** [comment]
@rreusser I've made some effort in [6a66641c75d6a96dce58cf0da1467ef1ba71c841](https://github.com/isRuslan/vim-es6/commit/6a66641c75d6a96dce58cf0da1467ef1ba71c841).

So, template strings became look like this:

![str](https://cloud.githubusercontent.com/assets/2136166/9419419/1fe51fb6-4864-11e5-9351-1e31427b6a8d.jpg)

Is it desired result?

**Comment by bdryanovski** [comment]
![screen shot 2015-09-07 at 11 13 45](https://cloud.githubusercontent.com/assets/204564/9712184/a34a339c-5551-11e5-8583-9dbeba23a995.png)

**Comment by iamsebastian** [comment]
@bdryanovski It is also not at 100% here, but I do not have coloured multilines.
![screenshot from 2015-11-17 14-30-40](https://cloud.githubusercontent.com/assets/1620425/11212729/e294b69e-8d37-11e5-9822-7ebcbb74c072.png)

**Comment by sethyuan** [comment]
@isRuslan , it seems nested template strings are not parsed correctly.
![image](https://cloud.githubusercontent.com/assets/3410293/12395408/57601268-be3c-11e5-9744-6cc975f0a76a.png)

**Comment by isRuslan** [comment]
Thanks for reporting, I'll check that.

**Comment by isRuslan** [comment]
@sethyuan I've updated template strings, it should solves your problem.
![multi](https://cloud.githubusercontent.com/assets/2136166/12473001/236e8b44-c01f-11e5-8096-3eb2b28c3a79.jpg)

**Comment by sethyuan** [comment]
@isRuslan, sweet! It works perfectly. Thanks for this great plugin!

**Comment by isRuslan** [comment]
@sethyuan nice :) closing issue then.
