### ISSUE TITLE
4MB gif in repo

### ISSUE THREAD

**Issue by ahw** [isRuslan/vim-es6#7]
Hey thanks for writing this, so far it works quite well. I noticed the example gif in your README has been committed directly to git. Since the file is 4MB, it makes cloning the repo a lot slower than it needs to be, particularly over coffee shop wifi. You may want to consider hosting the image somewhere external and just linking to it from the README so it doesn't need to live in source control and bloat the repo.

**Comment by isRuslan** [comment]
Yes, sample gif should definitely be [host separately](https://github.com/isRuslan/vim-es6/commit/735b9f7af3fc4fa4ef0500d196a9af5da3f80baa).
Thank you for reporting such an obvious thing :flushed:
