### ISSUE TITLE
String highlights stopped working

### ISSUE THREAD

**Issue by schnie** [isRuslan/vim-es6#8]
First off, thanks for the great plugin!  I'm new to vim so i'm not much help looking into issues yet, but I just pulled the latest commit and it appears to break string highlighting on all my import statements.

For example, with `import logger from '../util/logger';` the path string used to be highlighted green for me, but now it looks just like plain text.  I've reverted back to the previous commit and it works fine again.

Any ideas?  Thanks!

**Comment by isRuslan** [comment]
Hi @schnie please try to pull fresh version of plugin, we had some issues with string, but for now it should be fixed.

Point here if it is not.
